### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by marchermans** [diegomvh/ODataApiGen#1]
It would be nice if this project received a proper specification of the licence it falls under in its project Root.

Something like MIT, Apache, or GNU if you choose to keep it open source would be amazing.

Thanks for the nice project.

**Comment by diegomvh** [comment]
Thanks to you and apologize for the delay.

**Comment by marchermans** [comment]
@diegomvh So what is the licence now?

**Comment by diegomvh** [comment]
Hi, @OrionDevelopment 

How strange, I forgot to add the license.
Now yes, MIT license.
Thanks again
