### ISSUE TITLE
PUT instead of PATCH?

### ISSUE THREAD

**Issue by TheDevelolper** [diegomvh/ODataApiGen#11]
I have the following controller action: 

``` csharp
        [HttpPatch]
        [Produces("application/json")]
        public ActionResult<bool> Patch([FromODataUri] string key, ODataActionParameters parameters)
        {
            ...
        }
```

The generator seems to create a PUT request for this in the client library instead of a patch?

**Comment by diegomvh** [comment]
Hi @FacePalmDev 

The code generator will create services for each EntitySet inheriting from [ODataEntityService](https://github.com/diegomvh/angular-odata/blob/9a215a674829262d0b9b8fb43cb7570fdef2ea04/projects/angular-odata/src/lib/services/entity.ts#L10) (in the next version it changes the name to `ODataEntitySetService`)
In my effort to create specific names for services that differ from HTTP verbs, the names for the methods that occurred to me are:

**create** perform a HTTP **post**
**update** perform a HTTP **put**
**assign** perform a HTTP **patch**
**destroy** perform a HTTP **delete**

Maybe assign isn't the happiest of names :)

The services also have the shortcuts `fetchOrCreate` and` save`

Regards

**Comment by TheDevelolper** [comment]
Thank you for the answer!! I will try this  over the next few days and I'll close the ticket.
