### ISSUE TITLE
ODataApiGen ignore my local $metadata.xml and generate TrinPin services instead

### ISSUE THREAD

**Issue by brud** [diegomvh/ODataApiGen#12]
Hi @diegomvh, thanks for great package, but it seems to work incorrectly on my environment.

I'm on Windows 10 with latest updates, try to run command on cmd.exe: 
`docker run -it --rm -v %cd%:/local diegomvh/odataapigen Name=Odata MetadataFile=/local/$metadata.xml Output=/local`
and get odata directory with TrinPin services/entities/schemas/etc

I've tried to replace `$` to `%24` - no effect.
If I pass an unexsisting filename - exception throws.

Thats my $metadata.xml in zip (generates by Microsoft.AspNetCore.OData 8.0.0-rc)
[$metadata.zip](https://github.com/diegomvh/ODataApiGen/files/6326356/metadata.zip)

**Comment by diegomvh** [comment]
Hi @brud 

Try with

```bash
docker run -it --rm -v %cd%:/local diegomvh/odataapigen Name=Odata Metadata=file:///local/$metadata.xml Output=/local
```

thanks for giving the library a try
regards

PD: #3

**Comment by brud** [comment]
@diegomvh thanks, it helps :)
