### ISSUE TITLE
List of Enums are generated as single Enum properties

### ISSUE THREAD

**Issue by magbeat** [diegomvh/ODataApiGen#16]
Hi there,

thanks very much for the project!

We have a problem generating the typescript interfaces for a list of enum values.

The API model (in c#) has a list of enum property:

```
public class Comment
{
    ...
    public List<Audience> Audiences { get; set; } = new();
    ...
}
```

with the enum:

```
public enum Audience
{
    Public,
    Internal
}
```

The generator generates the interface in the form of:
```
export interface Comment {
    ...
    audiences: Audience;
    ...
}
```
instead of:
```
export interface Comment {
    ...
    audiences: Audience[];
    ...
}
```

**Comment by diegomvh** [comment]
Hi @magbeat 
Thank you very much!
