### ISSUE TITLE
Enums with FlagsAttribute

### ISSUE THREAD

**Issue by TheAifam5** [diegomvh/ODataApiGen#2]
Hey!

I like your project. Could you tell me if the enums with [Flag] attrubite are supported? OData likes to return them as comma-separated string.

OData filtering has something like `has` operator which is used as follow:
`$filter=type has Project.WebApi.Common'FirstType'`,
or if the `StringAsEnumResolver` or `UnqualifiedCallAndEnumPrefixFreeResolver` is enabled, then:
`$filter=type has 'FirstType'`.

Regards,
TheAifam5

**Comment by diegomvh** [comment]
Hi @TheAifam5 
Thanks for your comment, at the moment are not supported... but in base of your issue i added the feature of read the `IsFlags` field on the metadata parsing.
i don't know yet how represent  the flag's property beside the enum for eventualy customize the query... maybe a const in the ts file...

Thanks again
Regards,
Diego

**Comment by diegomvh** [comment]
New version of the tool generate the ISFLAGS_ constant and a schema for every entity interface.

the angular-odata library use the schema and handle incoming and outgoing data

https://github.com/diegomvh/TripPinEntity/blob/c8ed877b124853b69125934ea0b73b63c609fb26/src/app/trippin/Microsoft/OData/SampleService/Models/TripPin/person.entity.ts#L30

Thanks

**Comment by TheAifam5** [comment]
Hey!

Thanks for that, but the issue is more about the bitwised flags, where one property can have multiple states like:
- Gender: is Male and Female but not unknown
- DrivingLicense: has A, and B and C, but not D, E, F, G...

In example of `DrivingLicense` the bitwise flags where the enum in C# has `Flag` attribute, I will be able to get all drivers with `A` `B` `C` driver licenses and depends on the query if I want to show all drivers which have ABC, or if any of them has A or B or C.

OData will encode/decode that like:
```json
"gender": "male, female"
```

Also, when using it in query:
```
$filter=gender has Microsoft.OData.SampleService.Models.TripPin.PersonGender'male' and gender has Microsoft.OData.SampleService.Models.TripPin.PersonGender'female'
```
but that query will not return result when the Person has only `male` or `female` - this query requires both.

Another example of query:
```
$filter=(drivingLicense has DrivingLicense'a' and drivingLicense has DrivingLicense'b') or drivingLicense has DrivingLicense'c'
```

Will that work now? :D

EDIT:
I‘m gonna check that tomorrow (UTC+1) and if I find a little bit time, make a PR.

Regards,
TheAifam5

**Comment by diegomvh** [comment]
In te development branch of angular-odata the schema has the resposabiliy of handle with the data from server
If the field has `isFlags=true` the parse method create the correct numeric value for all flags thats arrive in the request and in the toJSON method serialize the number by unpacking every flag in the correct string value.... at the moment the `stringAsEnum` option in the config is not use, but soon will do

Thanks again
And apologis for my short english vocavulary

 https://github.com/diegomvh/angular-odata/blob/f74328e3f4ac84ebff5e8b58fb01435951f27e96/src/lib/odata-request/schema.ts#L96
