### ISSUE TITLE
New Feature: Ability to pass in $metadata.xml file

### ISSUE THREAD

**Issue by kevindstanley1988** [diegomvh/ODataApiGen#3]
When working locally in vscode and doing rapid development between the Odata web server and the angular web client it would be really nice to either be able to access localhost like "http://localhost/odata/$metadata" (doesn't seem likely with the way docker works) or send into the docker through command line a $metadata.xml file with a different parameter like 

`docker run -it --rm -v C:\temp\test:/local diegomvh/odataapigen Name=TripPin StringAsEnum=true MetadataFile=c:\$metadata.xml Output=/local`

**Comment by diegomvh** [comment]
The XDocument.load() works with URIs and identifies the source to load the contents of the xml file.
I guess something like:

```bash
docker run -it --rm -v C:\temp\test:/local diegomvh/odataapigen Name=TripPin StringAsEnum=true Metadata=file:///local/trippin.xml Output=/local
```
It should work

Where `trippin.xml` should be on the path to map inside the container **c:\temp\test** according to the example.

regards

**Comment by diegomvh** [comment]
Create an example that uses a local file to generate the schema.
[MsGraph](https://github.com/diegomvh/ODataApiGen/blob/master/Examples/MsGraph/msgraph.sh)

regards
